---
# This role contains common plays that will run on all nodes.

# TODO: Review those sources for more security
- name: Put the correct sources.list file
  template: backup=yes
            src=sources.list.j2
            dest=/etc/apt/sources.list

- name: Check if vim is already installed.
  stat: path=/usr/bin/vim
  register: vim_installed

- name: Update apt cache if vim not installed
  apt: update_cache=yes
  when: vim_installed.stat.exists == false

# TODO: Maybe less time?, i don't know, maybe don't
- name: Update apt cache if not done today
  apt: update_cache=yes cache_valid_time=86400

- name: installing the packages for all the hosts
  apt: pkg={{ item }} state=present
  with_items: "{{ all_packages }}"

- name: Remove password authentication from ssh
  replace:
    dest=/etc/ssh/sshd_config
    regexp='\#PasswordAuthentication yes'
    replace='PasswordAuthentication no'

- name: Add alias 'l' for ls
  replace:
    dest=/home/{{ project.user }}/.bashrc
    regexp='\#alias l'
    replace='alias l'

